package com.libby.letsbookit.daos;

import com.libby.letsbookit.model.Frequencies;
import com.libby.letsbookit.model.Market;
import com.libby.letsbookit.repositories.MarketRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

// QUESTION: Is this description accurate?
/**
 * MarketService Class provides the business logic for the client to interact with the database.
 */
@Service
public class MarketService {

  // connects to the repository
  @Autowired
  private MarketRepository marketRepository;


  /**
   *Provides the business logic to create a market object and then add it as a record to the
   * database.
   *
   * @param name the name of the market.
   * @param description the description of the market.
   * @param frequency the frequency that the market is held.
   * @param contactNumber the contact phone number for the market.
   * @param contactEmail the contact email for the market.
   * @param website the website URL for the market.
   * @param socialMedia the social media link for the market.
   * @return The autogenerated id of the market.
   */
  public Integer createMarket(String name, String description, Frequencies frequency,
                              Integer contactNumber, String contactEmail, String website,
                              String socialMedia) {
    Market market = new Market(name, description, frequency, contactNumber, contactEmail, website,
                               socialMedia);
    this.marketRepository.save(market);
    return market.getId();
  }

  /**
   * Provides the business logic to update a market object in the database.
   *
   * @param id the primary key, unique id of the market.
   * @param name the name of the market.
   * @param description the description of the market.
   * @param frequency the frequency that the market is held.
   * @param contactNumber the contact phone number for the market.
   * @param contactEmail the contact email for the market.
   * @param website the website URL for the market.
   * @param socialMedia the social media link for the market.
   * @return The autogenerated id of the market.
   */
  public Integer updateMarket(Integer id, String name, String description, Frequencies frequency,
      Integer contactNumber, String contactEmail, String website,
      String socialMedia) {
    Market market = this.findMarketById(id);
    market.setName(name);
    market.setDescription(description);
    market.setFrequency(frequency);
    market.setContactNumber(contactNumber);
    market.setContactEmail(contactEmail);
    market.setWebsite(website);
    market.setSocialMedia(socialMedia);
    this.marketRepository.save(market);
    return market.getId();
  }

  // QUESTION: consistent naming convention for function, match UserService or match assignment documentation?
  // QUESTION: Does this break anything doing it this way? I saw UserService had getById call a getUser helper function.
  /**
   * Provides the business logic to get a market from the database, when given the id, or primary
   * key, of the market.
   *
   * @param id the primary key, unique id of the market.
   * @return The market of the assigned id number.
   */
  public Market findMarketById(Integer id) {
    Optional<Market> market = this.marketRepository.findById(id);
    return market.get();
  }

  /**
   * Provides the business logic to delete a market from the database, when given the id,
   * or primary key of the market.
   *
   * @param id the primary key, unique id of the market.
   */
  public void deleteMarket(Integer id) {
    this.marketRepository.deleteById(id);
  }

  // QUESTION: consistent naming convention for function, match UserService or match assignment documentation?
  /**
   * Provides the business logic to get all markets from the database.
   *
   * @return A list of all markets in the database.
   */
  public List<Market> findAllMarkets() {
    return (List<Market>) this.marketRepository.findAll();
  }


}
