package com.libby.letsbookit.service;

import com.libby.letsbookit.model.Stand;
import com.libby.letsbookit.repositories.StandRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * StandService Class provides business logic for the client to interact with the database.
 */
@Service
public class StandService {

  // connects to the repository
  @Autowired
  private StandRepository standRepository;

  /**
   * Provides the business logic to create a stand object and then adds it as a record to the
   * database.
   *
   * @param eventId the id of the event the stand belongs to.
   * @param tableName the table name that helps identify the stand.
   * @param tableNotes the table notes that describe the stand.
   * @param booked the booked status of the stand.
   * @param price the price it costs to rent the stand.
   * @return The autogenerated id of the market.
   */
  public Integer createStand(Integer eventId, String tableName, String tableNotes, Boolean booked,
                             Float price) {
    Stand stand = new Stand(eventId, tableName, tableNotes, booked, price);
    this.standRepository.save(stand);
    return stand.getId();
  }


  /**
   * Provides the business logic to update the stand object in the database.
   *
   * @param id the primary key, unique id of the stand.
   * @param eventId the id of the event the stand belongs to.
   * @param tableName the table name that helps identify the stand.
   * @param tableNotes the table notes that describe the stand.
   * @param booked the booked status of the stand.
   * @param price the price it costs to rent the stand.
   * @return The autogenerated id of the stand.
   */
  public Integer updateStand(Integer id, Integer eventId, String tableName,
      String tableNotes, Boolean booked, Float price) {
    Stand stand = (Stand) this.findStandById(id);
    stand.setEventId(eventId);
    stand.setTableName(tableName);
    stand.setTableNotes(tableNotes);
    stand.setBooked(booked);
    stand.setPrice(price);
    this.standRepository.save(stand);
    return stand.getId();
  }

  /**
   * Provides the business logic to get a stand from the database, when given the id, or primary
   * key, of the stand.
   *
   * @param id the primary key, unique id of the stand.
   * @return The stand of the assigned id number.
   */
  public Stand findStandById(Integer id) {
    Optional<Stand> stand = this.standRepository.findById(id);
    return stand.get();
  }

  /**
   * Provides the business logic to delete a stand from the database, when given the id,
   * or primary key of the stand.
   *
   * @param id the primary key, unique id of the stand.
   */
  public void deleteStand(Integer id) {
    this.standRepository.deleteById(id);
  }

  /**
   * Provides the business logic to get all stands from the database.
   *
   * @return A list of all stands in the database.
   */
  public List<Stand> findAllStands() {
    return (List<Stand>) this.standRepository.findAll();
  }
}
