package com.libby.letsbookit.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Class that represents a market.
 */
@Entity
@Table(name = "markets")
public class Market {

  // the unique id that is autogenerated
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;
  @Column(name = "market_name")
  private String name;
  @Column(name = "description")
  private String description;
  @Column(name = "frequency")
  private Frequencies frequency;
  @Column(name = "contact_number")
  private Integer contactNumber;
  @Column(name = "contact_email")
  private String contactEmail;
  @Column(name = "website")
  private String website;
  @Column(name = "social_media")
  private String socialMedia;

  /**
   * Constructor for market.
   *
   * @param name the name of the market.
   * @param description the description of the market.
   * @param frequency the frequency that the market is held.
   * @param contactNumber the contact phone number for the market.
   * @param contactEmail the contact email for the market.
   * @param website the website URL for the market.
   * @param socialMedia the social media link for the market.
   */
  public Market(String name, String description, Frequencies frequency,
      Integer contactNumber, String contactEmail, String website, String socialMedia) {
    this.name = name;
    this.description = description;
    this.frequency = frequency;
    this.contactNumber = contactNumber;
    this.contactEmail = contactEmail;
    this.website = website;
    this.socialMedia = socialMedia;
  }

  /**
   * Constructor with no parameters for market.
   */
  public Market() {

  }

  /**
   * Gets the id of the market.
   *
   * @return The id of the market.
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the id of the market.
   *
   * @param id The id of the market.
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Gets the name of the market.
   *
   * @return The name of the market.
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the name of the market.
   *
   * @param name The name of the market.
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the description of the market.
   *
   * @return The description of the market.
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the description of the market.
   *
   * @param description The description of the market.
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Gets the frequency of the market.
   *
   * @return The frequency of the market.
   */
  public Frequencies getFrequency() {
    return frequency;
  }

  /**
   * Sets the frequency of the market.
   *
   * @param frequency The frequency of the market.
   */
  public void setFrequency(Frequencies frequency) {
    this.frequency = frequency;
  }

  /**
   * Gets the contact phone number of the market.
   *
   * @return The contact phone number of the market.
   */
  public Integer getContactNumber() {
    return contactNumber;
  }

  /**
   * Sets the contact phone number of the market.
   *
   * @param contactNumber The contact phone number of the market.
   */
  public void setContactNumber(Integer contactNumber) {
    this.contactNumber = contactNumber;
  }

  /**
   * Gets the contact email address of the market.
   *
   * @return The contact email address of the market.
   */
  public String getContactEmail() {
    return contactEmail;
  }

  /**
   * Sets the contact email address of the market.
   *
   * @param contactEmail The contact email address of the market.
   */
  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  /**
   * Gets the website URL of the market.
   *
   * @return The website URL of the market.
   */
  public String getWebsite() {
    return website;
  }

  /**
   * Sets the website URL of the market.
   *
   * @param website The website URL of the market.
   */
  public void setWebsite(String website) {
    this.website = website;
  }

  /**
   * Gets the social media of the market.
   *
   * @return The social media of the market.
   */
  public String getSocialMedia() {
    return socialMedia;
  }

  /**
   * Sets the social media of the market.
   *
   * @param socialMedia The social media of the market.
   */
  public void setSocialMedia(String socialMedia) {
    this.socialMedia = socialMedia;
  }
}
