package com.libby.letsbookit.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * A class that represents a stand that is at a scheduled event that can be booked by a vendor
 */

@Entity
@Table(name="stands")
public class Stand {

  // the unique id that is autogenerated
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  @Column(name = "table_name")
  private String name;
  @Column(name = "table_notes")
  private String notes;
  @Column(name = "booked")
  private Boolean booked;
  @Column(name = "price")
  private Float price;

  // TODO: Verify if this is properly implemented
  @ManyToOne
  @JoinColumn(name="event_id")
  @JsonIgnore
  private Event event;

  @ManyToOne
  @JoinColumn(name = "vendor_id")
  @JsonIgnore
  private Vendor vendor;

  // TODO: Verify that this is right!
  /**
   * Constructor for unbooked stand.
   *
   * @param name the table name that helps identify the stand.
   * @param notes the table notes that describe the stand.
   * @param price the price it costs to rent the stand.
   * @param event the event the stand belongs to.
   */
  public Stand(String name, String notes, Float price, Event event) {

    this.name = name;
    this.notes = notes;
    this.booked = null;
    this.price = price;
    this.event = event;
    this.vendor = null;
  }

  /**
   * Constructor for stand.
   *
   * @param name the table name that helps identify the stand.
   * @param notes the table notes that describe the stand.
   * @param booked the booked status of the stand.
   * @param price the price it costs to rent the stand.
   * @param event the event the stand belongs to.
   * @param vendor the vendor that has booked the stand.
   */
  public Stand(String name, String notes,
      Boolean booked, Float price, Event event, Vendor vendor) {

    this.name = name;
    this.notes = notes;
    this.booked = booked;
    this.price = price;
    this.event = event;
    this.vendor = vendor;
  }



  /**
   * Constructor with no parameters for Stand.
   */
  public Stand() {
  }

  /**
   * Gets the id of the stand.
   *
   * @return The id of the stand.
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the id of the stand.
   *
   * @param id The id of the stand.
   */
  public void setId(Integer id) {
    this.id = id;
  }



  /**
   * Gets the table name of the stand.
   *
   * @return The table name of the stand.
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the table name of the stand.
   *
   * @param name The table name of the stand.
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the table notes of the stand.
   *
   * @return The table notes of the stand.
   */
  public String getNotes() {
    return notes;
  }

  /**
   * Sets teh table notes of the stand.
   *
   * @param notes The table notes of the stand.
   */
  public void setNotes(String notes) {
    this.notes = notes;
  }

  /**
   * Gets the booking status of the stand.
   *
   * @return True if stand is booked, False otherwise.
   */
  public Boolean getBooked() {
    return booked;
  }

  /**
   * Sets the booking status of the stand.
   *
   * @param booked The booking status of the stand.
   */
  public void setBooked(Boolean booked) {
    this.booked = booked;
  }

  /**
   * Gets the price to book the stand.
   *
   * @return The price to book the stand.
   */
  public Float getPrice() {
    return price;
  }

  /**
   * Sets the price to book the stand.
   *
   * @param price The price to book the stand.
   */
  public void setPrice(Float price) {
    this.price = price;
  }

  /**
   * Gets the event the stand belongs to.
   *
   * @return The associated event.
   */
  public Event getEvent() {
    return event;
  }

  /**
   * Sets the associated event.
   *
   * @param event The associated event.
   */
  public void setEvent(Event event) {
    this.event = event;
  }

  /**
   * Gets the vendor that booked the stand.
   *
   * @return The associated vendor.
   */
  public Vendor getVendor() {
    return vendor;
  }

  /**
   * Sets the vendor that has the stand booked.
   *
   * @param vendor The associated vendor.
   */
  public void setVendor(Vendor vendor) {
    this.vendor = vendor;
  }
}
