package com.libby.letsbookit.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;


/**
 * A class that represents a stand that is at a scheduled event that can be booked by a vendor
 */

@Entity
@Table(name="stands")
public class Stand {

  // the unique id that is autogenerated
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  // TODO: Verify if this is properly implemented
  @JoinColumn(name="event_Id")
  private Integer eventId;

  @Column(name = "table_name")
  private String tableName;
  @Column(name = "table_notes")
  private String tableNotes;
  @Column(name = "booked")
  private Boolean booked;
  @Column(name = "price")
  private Float price;

  /**
   * Constructor for stand.
   *
   * @param eventId the id of the event the stand belongs to.
   * @param tableName the table name that helps identify the stand.
   * @param tableNotes the table notes that describe the stand.
   * @param booked the booked status of the stand.
   * @param price the price it costs to rent the stand.
   */
  public Stand(Integer eventId, String tableName, String tableNotes,
      Boolean booked, Float price) {
    this.eventId = eventId;
    this.tableName = tableName;
    this.tableNotes = tableNotes;
    this.booked = booked;
    this.price = price;
  }

  /**
   * Constructor with no parameters for Stand.
   */
  public Stand() {
  }

  /**
   * Gets the id of the stand.
   *
   * @return The id of the stand.
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the id of the stand.
   *
   * @param id The id of the stand.
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Gets the id of the event the stand belongs to.
   *
   * @return The id of the associated event.
   */
  public Integer getEventId() {
    return eventId;
  }

  /**
   * Sets the event id of the associated event.
   *
   * @param eventId The id of the associated event.
   */
  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  /**
   * Gets the table name of the stand.
   *
   * @return The table name of the stand.
   */
  public String getTableName() {
    return tableName;
  }

  /**
   * Sets the table name of the stand.
   *
   * @param tableName The table name of the stand.
   */
  public void setTableName(String tableName) {
    this.tableName = tableName;
  }

  /**
   * Gets the table notes of the stand.
   *
   * @return The table notes of the stand.
   */
  public String getTableNotes() {
    return tableNotes;
  }

  /**
   * Sets teh table notes of the stand.
   *
   * @param tableNotes The table notes of the stand.
   */
  public void setTableNotes(String tableNotes) {
    this.tableNotes = tableNotes;
  }

  /**
   * Gets the booking status of the stand.
   *
   * @return True if stand is booked, False otherwise.
   */
  public Boolean getBooked() {
    return booked;
  }

  /**
   * Sets the booking status of the stand.
   *
   * @param booked The booking status of the stand.
   */
  public void setBooked(Boolean booked) {
    this.booked = booked;
  }

  /**
   * Gets the price to book the stand.
   *
   * @return The price to book the stand.
   */
  public Float getPrice() {
    return price;
  }

  /**
   * Sets the price to book the stand.
   *
   * @param price The price to book the stand.
   */
  public void setPrice(Float price) {
    this.price = price;
  }

}
