package com.libby.letsbookit.model;


import com.fasterxml.jackson.annotation.JsonProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.constraints.Email;

/**
 * Class that represents a vendor.
 */
@Entity
@Table(name = "vendors")
public class Vendor {

  // the unique id that is autogenerated
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  @Column(name = "vendor_name")
  @JsonProperty
  private String name;

  @Column(name = "vendor_description")
  @JsonProperty
  private String description;

  // TODO: For future, will need to convert data type to long rather than into allow for larger numbers
  @Column(name = "contact_number")
  @JsonProperty
  private Integer contactNumber;

  @Column(name = "contact_email")
  @JsonProperty
  @Email
  private String contactEmail;

  @Column(name = "website")
  @JsonProperty
  private String website;

  @Column(name = "social_media")
  @JsonProperty
  private String socialMedia;

  /**
   * Constructor for vendor.
   *
   * @param name the name of the vendor.
   * @param description the description of the vendor.
   * @param contactNumber the contact phone number for the vendor.
   * @param contactEmail the contact email for the vendor.
   * @param website the website URL for the vendor.
   * @param socialMedia the social media link for the vendor.
   */
  public Vendor(String name, String description, Integer contactNumber, String contactEmail,
      String website, String socialMedia) {
    this.name = name;
    this.description = description;
    this.contactNumber = contactNumber;
    this.contactEmail = contactEmail;
    this.website = website;
    this.socialMedia = socialMedia;
  }

  /**
   * Constructor with no parameters for vendor.
   */
  public Vendor() {

  }

  /**
   * Gets the id of the vendor.
   *
   * @return The id of the vendor.
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the id of the vendor.
   *
   * @param id The id of the vendor.
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Gets the name of the vendor.
   *
   * @return The name of the vendor.
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the name of the vendor.
   *
   * @param name The name of the vendor.
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the description of the vendor.
   *
   * @return The description of the vendor.
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the description of the vendor.
   *
   * @param description The description of the vendor.
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Gets the contact phone number of the vendor.
   *
   * @return The contact phone number of the vendor.
   */
  public Integer getContactNumber() {
    return contactNumber;
  }

  /**
   * Sets the contact phone number of the vendor.
   *
   * @param contactNumber The contact phone number of the vendor.
   */
  public void setContactNumber(Integer contactNumber) {
    this.contactNumber = contactNumber;
  }

  /**
   * Gets the contact email address of the vendor.
   *
   * @return The contact email address of the vendor.
   */
  public String getContactEmail() {
    return contactEmail;
  }

  /**
   * Sets the contact email address of the vendor.
   *
   * @param contactEmail The contact email address of the vendor.
   */
  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  /**
   * Gets the website URL of the vendor.
   *
   * @return The website URL of the vendor.
   */
  public String getWebsite() {
    return website;
  }

  /**
   * Sets the website URL of the vendor.
   *
   * @param website The website URL of the vendor.
   */
  public void setWebsite(String website) {
    this.website = website;
  }

  /**
   * Gets the social media of the vendor.
   *
   * @return The social media of the vendor.
   */
  public String getSocialMedia() {
    return socialMedia;
  }

  /**
   * Sets the social media of the vendor.
   *
   * @param socialMedia The social media of the vendor.
   */
  public void setSocialMedia(String socialMedia) {
    this.socialMedia = socialMedia;
  }

}
