package com.libby.letsbookit.daos.userservice;

import com.libby.letsbookit.model.User.MarketStaff;
import com.libby.letsbookit.model.User.Roles;
import com.libby.letsbookit.model.User.User;
import com.libby.letsbookit.repositories.userrepository.UserBaseRepository;
import java.time.LocalDateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Subtype class that inherits from abstract class UserService.
 */
@Service
public class MarketStaffService extends UserService {

  // connects to the repository
  @Autowired
  private UserBaseRepository marketStaffRepository;

  /**
   * Provides the business logic to create a user object and then add it as a record to the
   * database.
   *
   * @param username the username of the user creating a new user account.
   * @param password the password of the user.
   * @param firstName the first name of the user.
   * @param lastName the last name of the user.
   * @param email the email of the user.
   * @param dateOfBirth the date of birth of the user.
   * @param role the role of the user.
   * @return The autogenerated id of the user.
   */
  @Override
  public Integer createUser(String username, String password, String firstName, String lastName,
      String email, String dateOfBirth, Roles role) {
    LocalDateTime objectDateOfBirth = super.helperLocalDateTime(dateOfBirth);
    User marketStaff = new MarketStaff(username, password, firstName, lastName, email, objectDateOfBirth, role);
    marketStaffRepository.save(marketStaff);
    return marketStaff.getId();
  }

  /**
   * Updates the user that is a market staff.
   * @param id the primary key, unique id of the user.
   * @param username the username of the user creating a new user account.
   * @param password the password of the user.
   * @param firstName the first name of the user.
   * @param lastName the last name of the user.
   * @param email the email of the user.
   * @param dateOfBirth the date of birth of the user.
   * @param role the role of the user.
   * @return The autogenerated id of the user.
   */
  @Override
  public Integer updateUser(Integer id, String username, String password, String firstName,
      String lastName, String email, String dateOfBirth, Roles role) {
    // TODO: create a function in super class to avoid duplicate code
    MarketStaff ms = (MarketStaff) this.getById(id);
    ms.setUsername(username);
    ms.setPassword(password);
    ms.setFirstName(firstName);
    ms.setLastName(lastName);
    ms.setEmail(email);
    ms.setDateOfBirth(helperLocalDateTime(dateOfBirth));
    ms.setRole(role);
    this.marketStaffRepository.save(ms);
    return ms.getId();
  }
}
