package com.libby.letsbookit.controller;


import com.libby.letsbookit.service.MarketService;
import com.libby.letsbookit.model.Market;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


/**
 * MarketController class provides CRUD requests for the client to interact with the database.
 */
@CrossOrigin(origins = "http://localhost:3000")
@RestController
@RequestMapping("/markets")
public class MarketController {

  // connect with the service layer
  @Autowired
  private MarketService marketService;

  // POST Request

  /**
   * Client request to add new market to the database.
   *
   * @param market The new market to add to the database.
   * @return
   */
  @PostMapping(value = "/add-market")
  public ResponseEntity<Market> addMarket(@RequestBody Market market) {
    try {
      return new ResponseEntity<>(
          this.marketService.addMarket(market), HttpStatus.OK);

    } catch (Exception e) {
      return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
    }
  }

  // GET Requests

  /**
   * Gets all markets from the database.
   *
   * @return Returns HTTP status, if the request is good or bad, and also returns a list of all
   * markets in the database.
   */
  @GetMapping
  public ResponseEntity<List<Market>> findAllMarkets() {
    List<Market> markets = this.marketService.getALlMarkets();
    if (!markets.isEmpty()) {
      return new ResponseEntity<>(markets, HttpStatus.OK);
    } else {
      return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
  }


  // TODO: review and edit getUser documentation on UserController
  /**
   * Gets a market from the database when given an id.
   *
   * @param id the autogenerated id of the market
   * @return Returns HTTP status, if the request is good or bad, and also returns the market if a
   * successful request.
   */
  @GetMapping(value = "/{id}")
  public ResponseEntity<Market> findMarketById(@PathVariable Integer id) {
    Market market = this.marketService.findMarketById(id);
    if (market != null) {
      return new ResponseEntity<>(market, HttpStatus.OK);
    } else {
      return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
  }

  // PUT Request

  /**
   * Client request to update the Market record in the database given the id.
   *
   * @param id The primary key, unique id of the market.
   * @param market The Market object with the updated information.
   * @return The Market with the updated information.
   */
  @PutMapping(value = "/update/{id}")
  public ResponseEntity<Market> updateMarket(@PathVariable("id") Integer id, @RequestBody Market market) {
    try {
      return new ResponseEntity<>(this.marketService.updateMarket(id, market), HttpStatus.OK);
    } catch (Exception e) {
      return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
    }
  }

  // DELETE Request

  // QUESTION: UserController has deletePlace instead of deleteUser, Is this intentional?

  /**
   * Deletes a market from the database when given an id.
   *
   * @param id the primary key, unique id of the market.
   * @return Returns the HTTP status, if the request is good or bad.
   */
  @DeleteMapping(value = "/delete/{id}")
  public ResponseEntity<HttpStatus> deleteMarket(@PathVariable("id") Integer id) {
    try {
      this.marketService.deleteMarket(id);
      return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    } catch (Exception e) {
      return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
    }
  }

}
